#!/bin/sh
# Generate a daily note markdown file that mirrors the legacy Node implementation.
# Uses helper scripts in ./utils when available to populate dynamic sections.

set -eu

log_info() {
  printf 'ℹ️ %s\n' "$*"
}

log_warn() {
  printf '⚠️ %s\n' "$*"
}

# Ensure common tools are found even under cron (put /usr/local/bin first)
PATH="/usr/local/bin:/usr/bin:/bin:${PATH:-}"

log_info "Starting daily note generation"

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
commit_helper="$script_dir/utils/commit.sh"

# Match the legacy default vault path unless overridden and construct
# the periodic notes directory using the same path handling as the
# other non-legacy scripts.
vault_path="${VAULT_PATH:-/home/obsidian/vaults/Main}"
vault_root="${vault_path%/}"
periodic_dir="${vault_root}/Periodic Notes"
daily_note_dir="${periodic_dir%/}/Daily Notes"

log_info "Vault path: $vault_root"
log_info "Daily note directory: $daily_note_dir"

# Ensure the output directory exists
if [ ! -d "$daily_note_dir" ]; then
  log_warn "Periodic notes folder does not exist: $daily_note_dir"
  echo "❌ Periodic notes folder does not exist: $daily_note_dir" >&2
  echo "Edit generate-daily-note.sh to match your vault structure." >&2
  exit 1
fi

# Date helpers
today=$(date +%Y-%m-%d)
year=$(printf '%s' "$today" | cut -d- -f1)
month=$(printf '%s' "$today" | cut -d- -f2)
day=$(printf '%s' "$today" | cut -d- -f3)
quarter=$(( (10#$month + 2) / 3 ))
week_tag=$(date +%G-W%V)

log_info "Generating note for date: $today"

log_info "Preparing time block navigation"

time_blocks_nav=$(cat <<EOF_TB
## ⌚ Time Blocks
- [[Periodic Notes/Daily Notes/Subnotes/${today} - Wake Up|Wake Up]]
- [[Periodic Notes/Daily Notes/Subnotes/${today} - Morning|Morning]]
- [[Periodic Notes/Daily Notes/Subnotes/${today} - Afternoon|Afternoon]]
- [[Periodic Notes/Daily Notes/Subnotes/${today} - Evening|Evening]]
- [[Periodic Notes/Daily Notes/Subnotes/${today} - Night|Night]]

> [!tip] Power navigation
> - [[Weekly Routine]]
> - [[Stand on Business List]]
> - [[Comms Queue]]
> - [[Device Config Queue]]
> - [[Quick Wins List]]
> - [[Someday / Maybe]]
EOF_TB
)

# Portable yesterday/tomorrow (works on BSD/GNU date)
yesterday=$(TZ=UTC+24 date +%Y-%m-%d)
tomorrow=$(TZ=UTC-24 date +%Y-%m-%d)

file_path="${daily_note_dir%/}/${today}.md"

set -- "$file_path"

log_info "Primary daily note path: $file_path"

# Time block subnote placeholders + content
time_block_subnotes_dir="${daily_note_dir%/}/Subnotes"
mkdir -p "$time_block_subnotes_dir"

populate_block() {
  block_name="$1"   # e.g., "Morning"
  sh "$script_dir/utils/generate-day-plan.sh" --block "$block_name" 2>/dev/null || true
}

for subnote in "Wake Up" "Morning" "Afternoon" "Evening" "Night"; do
  subnote_path="${time_block_subnotes_dir%/}/${today} - ${subnote}.md"

  # Always (over)write content so it stays in sync with the plan:
  log_info "Generating subnote for block: $subnote"
  block_content="$(populate_block "$subnote")"

  {
    printf '# %s — %s\n\n' "$subnote" "$today"
    printf '<!-- autogenerated: filled from Daily Plan.md by generate-daily-note.sh; do not edit here -->\n\n'
    printf '%s\n\n' "$time_blocks_nav"
    printf '## From Daily Plan\n'
    if [ -n "$block_content" ]; then
      printf '%s\n' "$block_content"
    else
      printf '_No entries for this block._\n'
    fi
  } > "$subnote_path"

  # Add to commit list regardless of new/existing:
  set -- "$@" "$subnote_path"
  log_info "Subnote updated: $subnote_path"
done

# ----- Defaults as real multiline text (no literal \n) -----
f1_text=$(cat <<'EOF'
# 🏎️ Formula 1
⚠️ Could not load race data.
EOF
)

weekly_goal_text="⚠️ Weekly Goal section is empty."

pagan_header="### Pagan Timings"
moon_text="⚠️ Moon phase info unavailable."
season_text="⚠️ Seasonal turning info unavailable."

# ----- Optional dynamic sections (resolve paths from script_dir; do not require +x) -----
if [ -r "$script_dir/utils/f1-schedule-and-standings.sh" ]; then
  log_info "Fetching Formula 1 data"
  if output=$(sh "$script_dir/utils/f1-schedule-and-standings.sh"); then
    log_info "Formula 1 data retrieved"
    f1_text="$output"
  else
    status=$?
    log_warn "Formula 1 script failed with exit code $status, using fallback text"
  fi
else
  log_warn "Formula 1 script not found at $script_dir/utils/f1-schedule-and-standings.sh, using fallback text"
fi

if [ -r "$script_dir/utils/extract-weekly-goal.sh" ]; then
  log_info "Extracting weekly goal"
  if output=$(sh "$script_dir/utils/extract-weekly-goal.sh"); then
    log_info "Weekly goal extracted"
    weekly_goal_text="$output"
  else
    status=$?
    log_warn "Weekly goal script failed with exit code $status, using fallback text"
  fi
else
  log_warn "Weekly goal script not found at $script_dir/utils/extract-weekly-goal.sh, using fallback text"
fi

pagan_moon_script="$script_dir/utils/pagan-moon.sh"
if [ -r "$pagan_moon_script" ]; then
  log_info "Gathering pagan moon data"
  if output=$(sh "$pagan_moon_script"); then
    log_info "Pagan moon data retrieved"
    moon_text="$output"
  else
    status=$?
    log_warn "Pagan moon script failed with exit code $status, using fallback text"
  fi
else
  log_warn "Pagan moon script not found at $pagan_moon_script, using fallback text"
fi

pagan_seasons_script="$script_dir/utils/pagan-seasons.sh"
if [ -r "$pagan_seasons_script" ]; then
  log_info "Gathering pagan season data"
  if output=$(sh "$pagan_seasons_script"); then
    log_info "Pagan season data retrieved"
    season_text="$output"
  else
    status=$?
    log_warn "Pagan seasons script failed with exit code $status, using fallback text"
  fi
else
  log_warn "Pagan seasons script not found at $pagan_seasons_script, using fallback text"
fi

pagan_timings_text=$(printf '%s\n%s\n%s\n' "$pagan_header" "$moon_text" "$season_text")

# Daily Plan intro (day + purpose)
daily_plan_intro=""
day_plan_script="$script_dir/utils/generate-day-plan.sh"
if [ -r "$day_plan_script" ]; then
  log_info "Loading daily plan intro"
  if day_plan_output=$(sh "$day_plan_script" 2>/dev/null); then
    intro_lines=$(printf '%s\n' "$day_plan_output" | awk '
      /^# Daily Plan - / {in_today=1; next}
      in_today && /^## Preview of Tomorrow:/ {exit}
      in_today {
        if (!day && /^## /) {
          day=$0
          next
        }
        if (!focus && /^### /) {
          focus=$0
        }
      }
      END {
        if (day) print day;
        if (focus) print focus;
      }
    ')
    if [ -n "$intro_lines" ]; then
      log_info "Daily plan intro captured"
      daily_plan_intro="$intro_lines"
    else
      log_warn "Daily plan intro not found in output"
    fi
  else
    log_warn "Daily plan script failed, skipping intro"
  fi
else
  log_warn "Daily plan script not found, skipping intro"
fi

if [ -n "$daily_plan_intro" ]; then
  daily_plan_intro_section=$(printf '%s\n\n' "$daily_plan_intro")
else
  daily_plan_intro_section=""
fi

log_info "Writing daily note content"

# Compose note content to match the legacy template.
cat <<EOF_NOTE > "$file_path"
---
tags:
  - matter/daily-notes
---
<< [[Periodic Notes/Daily Notes/${yesterday}|${yesterday}]] | [[Periodic Notes/Daily Notes/${tomorrow}|${tomorrow}]] >>

${daily_plan_intro_section}${pagan_timings_text}

${time_blocks_nav}

## 🌤️ Yard Work Suitability
<!-- yard-work-check -->

---
${f1_text}

---
# Themes and Goals

## [[Yearly theme]] (2025)
The year of standing on business
[[Stand on Business List]]

## [[Season Theme]] (2025 Spring)
Yard work and home repairs

## 🎯 Weekly Goal
${weekly_goal_text}

---

# ☑️ Pending Tasks
### Stand on Business
\`\`\`tasks
not done
tags include #stand-on-business
\`\`\`

### Comms Queue
\`\`\`tasks
not done
tags include #comms-queue
\`\`\`

### Device Config
\`\`\`tasks
not done
tags include #device-config
\`\`\`

### Quick Wins
\`\`\`tasks
not done
tags include #quick-wins
\`\`\`

### Someday/Maybe
\`\`\`tasks
not done
tags include #someday-maybe
\`\`\`

---

# Periodic Notes

[[Periodic Notes/Weekly Notes/${week_tag}|This Week]]
[[Periodic Notes/Monthly Notes/${year}-${month}|This Month]]
[[Periodic Notes/Quarterly Notes/${year}-Q${quarter}|This Quarter]]
[[Periodic Notes/Yearly Notes/${year}|This Year]]

---

# Links
[[Weekly Routine]]
[[Consider Johnie]]
[[Daily Note Template]]
[[Daily Plan]]
[[Workout Schedule]]
EOF_NOTE

printf '✅ Daily note created at %s\n' "$file_path"

if [ -x "$commit_helper" ]; then
  log_info "Invoking commit helper"
  "$commit_helper" -c "daily note" "$vault_path" "daily note: $today" "$@"
else
  log_warn "Commit helper not found: $commit_helper"
  printf '⚠️ commit helper not found: %s\n' "$commit_helper" >&2
fi
