#!/bin/sh
# engine/log-sink.sh
#
# Logging sink lifecycle manager.
# Library-only. MUST be sourced by log.sh (wrapper-only).
#
# Owns:
#   - per-run log filename generation
#   - directory layout
#   - sink FD lifecycle
#   - latest pointer
#   - retention pruning
#
# Contract authority: CONTRACT v0.9 §2.2, §3.2, Appendix C.6
#
# IMPORTANT (v0.9+):
# - Wrapper-context validation (JOB_WRAP_ACTIVE=1) is owned by log.sh (facade).
# - This component enforces facade ownership (LOG_FACADE_ACTIVE=1).
# - Per-run log filenames MUST be generated by the logger subsystem.
# - Timestamp format is canonical: YYYY-MM-DD-HHMMSS (local) via datetime.sh.

# ---- guard: library-only ---------------------------------------------------

if (return 0 2>/dev/null); then
    : # sourced, OK
else
    echo "ERROR: log-sink.sh is a library and must be sourced, not executed" >&2
    exit 2
fi

case "${LOG_SINK_LOADED:-0}" in
    1) return 0 ;;
esac
LOG_SINK_LOADED=1

# ---- internal scratch ------------------------------------------------------

_ls_log_dir=
_ls_latest_link=
_ls_keep_count=
_ls_job=
_ls_ts=
_ls_base=
_ls_pattern=
_ls_sorted_list=
_ls_total=
_ls_delete_count=
_ls_delete_list=
_ls_path=
_ls_rel=
_ls_rm_rc=
_ls_rc=
_ls_msg=

# ---- helpers ---------------------------------------------------------------

_ls_err() {
    _ls_msg=$*
    _ls_msg=$(printf '%s' "$_ls_msg" | LC_ALL=C tr -d '[:cntrl:]')
    printf 'LOG_SINK: %s\n' "$_ls_msg" >&2
}

_ls_fail() {
    _ls_err "ERROR: $*"
    return 10
}

_ls_fail_misuse() {
    _ls_err "ERROR: $*"
    return 11
}

_ls_require_facade() {
    if [ "${LOG_FACADE_ACTIVE:-}" != "1" ]; then
        _ls_fail_misuse "invoked without facade context (LOG_FACADE_ACTIVE!=1)"
        return 11
    fi
    return 0
}

_ls_validate_job_name() {
    _ls_job=$1

    if [ -z "$_ls_job" ]; then
        _ls_fail_misuse "missing required env var: JOB_NAME"
        return 11
    fi

    # Only allow [A-Za-z0-9._-]
    if ! printf '%s' "$_ls_job" | LC_ALL=C grep -Eq '^[A-Za-z0-9._-]+$'; then
        _ls_fail_misuse "invalid JOB_NAME (allowed: [A-Za-z0-9._-]): $_ls_job"
        return 11
    fi

    if [ "$_ls_job" = "." ] || [ "$_ls_job" = ".." ]; then
        _ls_fail_misuse "invalid JOB_NAME ('.' and '..' are forbidden): $_ls_job"
        return 11
    fi

    return 0
}

_ls_mkdir_p() {
    if [ -d "$1" ]; then
        return 0
    fi
    mkdir -p "$1" || _ls_fail "cannot create directory: $1"
}

# ---- timestamp + per-run filename (sink-owned) -----------------------------

_ls_require_datetime() {
    # datetime.sh is sourced by log.sh before log-sink.sh in your stack.
    # We treat missing dt_now_local_log_ts as an operational failure because
    # the environment is wired but incomplete (internal bug / deployment issue).
    if ! command -v dt_now_local_log_ts >/dev/null 2>&1; then
        _ls_fail "datetime helper missing: dt_now_local_log_ts (expected from datetime.sh)"
        return 10
    fi
    return 0
}

_ls_generate_log_file_path() {
    # Generates and exports LOG_FILE = <log_dir>/<job>-YYYY-MM-DD-HHMMSS.log
    # Canonical timestamp comes from dt_now_local_log_ts (local sortable).
    _ls_require_datetime || return $?

    _ls_ts=$(dt_now_local_log_ts 2>/dev/null) || {
        _ls_fail "cannot obtain local timestamp (dt_now_local_log_ts failed)"
        return 10
    }

    # Enforce exact canonical shape defensively.
    if ! printf '%s' "$_ls_ts" | LC_ALL=C grep -Eq '^[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]-[0-9][0-9][0-9][0-9][0-9][0-9]$'; then
        _ls_fail "datetime returned non-canonical log timestamp: $_ls_ts"
        return 10
    fi

    _ls_base="${JOB_NAME}-${_ls_ts}.log"

    # No whitespace, no control chars, ASCII-safe basename.
    if ! printf '%s' "$_ls_base" | LC_ALL=C grep -Eq '^[A-Za-z0-9._-]+$'; then
        _ls_fail "generated log filename is not ASCII-safe: $_ls_base"
        return 10
    fi

    LOG_FILE="${_ls_log_dir}/${_ls_base}"
    export LOG_FILE
    return 0
}

# ---- retention -------------------------------------------------------------

_ls_prune_logs() {
    _ls_keep_count=${LOG_KEEP_COUNT-}

    # Contract (v0.9+ update):
    # - unset/empty => pruning disabled (0)  [façade SHOULD supply default, but sink stays safe]
    # - 0 => pruning disabled
    # - N>=1 => keep N most recent per-run logs
    # - negative or non-integer => misuse (11)

    if [ -z "${_ls_keep_count}" ]; then
        _ls_keep_count=0
    fi

    case "$_ls_keep_count" in
        -*)
            _ls_fail_misuse "invalid LOG_KEEP_COUNT (must be non-negative integer): $_ls_keep_count"
            return 11
            ;;
        *[!0-9]*)
            _ls_fail_misuse "invalid LOG_KEEP_COUNT (must be non-negative integer): $_ls_keep_count"
            return 11
            ;;
    esac
    [ "$_ls_keep_count" -gt 0 ] || return 0

    _ls_pattern="${_ls_job}-????-??-??-??????.log"

    _ls_sorted_list=$(
        find "$_ls_log_dir" -type f -name "$_ls_pattern" 2>/dev/null \
        | while IFS= read -r _ls_path; do
              # Directory-local retention:
              # keep only direct children of $_ls_log_dir (no recursion)
              _ls_rel=${_ls_path#"$_ls_log_dir"/}

              # If it contains a slash, its in a subdir -> exclude.
              if [ "${_ls_rel#*/}" != "$_ls_rel" ]; then
                  :
              else
                  printf '%s\n' "$_ls_path"
              fi
          done \
        | sort
    ) || {
        _ls_fail "prune list generation failed"
        return 10
    }

    [ -n "${_ls_sorted_list:-}" ] || return 0

    _ls_total=$(printf '%s\n' "$_ls_sorted_list" | awk 'END { print NR }') || {
        _ls_fail "prune count failed"
        return 10
    }

    [ "$_ls_total" -le "$_ls_keep_count" ] && return 0

    _ls_delete_count=$(( _ls_total - _ls_keep_count ))

    _ls_delete_list=$(
        printf '%s\n' "$_ls_sorted_list" \
        | awk -v del="$_ls_delete_count" 'NR <= del { print }'
    ) || {
        _ls_fail "prune selection failed"
        return 10
    }

    [ -n "${_ls_delete_list:-}" ] || return 0

    _ls_rc=0
    while IFS= read -r _ls_path; do
        [ -n "$_ls_path" ] || continue
        rm -f "$_ls_path"
        _ls_rm_rc=$?
        if [ "$_ls_rm_rc" -ne 0 ]; then
            _ls_fail "cannot delete old log: $_ls_path (rm exit=$_ls_rm_rc)"
            _ls_rc=10
            break
        fi
    done <<END_DELETE
$_ls_delete_list
END_DELETE

    return $_ls_rc
}

# ---- public API ------------------------------------------------------------

log_sink_init() {
    _ls_require_facade || return $?
    _ls_validate_job_name "${JOB_NAME:-}" || return $?

    # Layout is logger-owned (bucket placement + directories).
    # LOG_ROOT may be provided by wrapper as an override. Default is repo-relative.
    LOG_ROOT=${LOG_ROOT:-"./logs"}

    if [ -z "${LOG_BUCKET:-}" ]; then
        _ls_fail_misuse "missing required env var: LOG_BUCKET"
        return 11
    fi

    _ls_log_dir="${LOG_ROOT}/${LOG_BUCKET}"
    _ls_latest_link="${LOG_ROOT}/${LOG_BUCKET}/${JOB_NAME}-latest.log"

    _ls_mkdir_p "$_ls_log_dir" || return $?

    _ls_generate_log_file_path || return $?

    # Ensure fd 3 is free before opening (POSIX-safe)
    exec 3>&- 2>/dev/null || :

    exec 3>>"$LOG_FILE" || {
        _ls_fail "cannot open log file: $LOG_FILE"
        return 10
    }

    ln -sf "$LOG_FILE" "$_ls_latest_link" || {
        _ls_fail "cannot update latest log symlink: $_ls_latest_link"
        return 10
    }

    _ls_prune_logs || return $?
    return 0
}

log_sink_close() {
    _ls_require_facade || return $?
    exec 3>&- 2>/dev/null || :
    return 0
}

# ---- internal API (logger subsystem only) ----------------------------------

_ls_write_line() {
    _ls_require_facade || return $?
    printf '%s\n' "$1" >&3 2>/dev/null || {
        _ls_fail "failed to write log line to fd 3 (sink not open?)"
        return 10
    }
    return 0
}
